# appveyor configuration. See http://www.appveyor.com/docs/appveyor-yml

before_build:
  - curl -fsS -o waf https://waf.io/waf-1.8.20
  - curl -fsS -o waf.bat https://raw.githubusercontent.com/waf-project/waf/master/utils/waf.bat

build_script:
  - waf configure build --verbose
